### ISSUE TITLE
error: variable 'ili' is used uninitialized whenever 'if' condition is false

### ISSUE THREAD

**Issue by dmikushin** [flang-compiler/flang#1375]
clang-16 is saying "You shall not pass" here:

```
classic-flang                 | /classic-flang/src/classic-flang/tools/flang2/flang2exe/expsmp.cpp:2687:8: error: variable 'ili' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
classic-flang                 |     if(opc == IM_ETARGETDATA) {
classic-flang                 |        ^~~~~~~~~~~~~~~~~~~~~
classic-flang                 | /classic-flang/src/classic-flang/tools/flang2/flang2exe/expsmp.cpp:2692:15: note: uninitialized use occurs here
classic-flang                 |     chk_block(ili);
classic-flang                 |               ^~~
```

**Comment by bryanpkc** [comment]
Thanks for reporting this. We fixed a bunch of `-Wsometimes-uninitialized` warnings under `tools/flang2/` in 319e967cc43e, but this one had escaped because the `OMP_OFFLOAD_LLVM` macro is unsupported, and we don't build with it defined.

**Comment by dmikushin** [comment]
@kiranchandramohan what commerical compilers **based on this code** are currently in use?

**Comment by kiranchandramohan** [comment]
From the Readme:
Classic Flang is used in several downstream commercial projects like the [AMD](https://developer.amd.com/amd-aocc/), [Arm](https://www.arm.com/products/development-tools/server-and-hpc/allinea-studio/fortran-compiler) and [Huawei](https://support.huaweicloud.com/intl/en-us/ug-bisheng-kunpengdevps/kunpengbisheng_06_0001.html) compilers, ...

The Arm compiler does not have offloading support. FWIU, there is support in AOCC and Bisheng.

Since Classic Flang was derived from pgfortran/nvfortran, there is support in nvfortran . But I am not sure whether it is based on this code or completely new code.

**Comment by bryanpkc** [comment]
Correction: BiSheng has kept offloading disabled at the moment. Only AOCC and nvfortran support offloading.

**Comment by dmikushin** [comment]
From what I understand, over the past few years Huawei is the only company upstreaming their changes to this repository. Did AMD or Arm ever upstream any recent contribution here, or to any other public repository that you know of?

**Comment by kiranchandramohan** [comment]
I don't know what you are getting at here. But since the eventual plan is to replace Classic Flang with llvm/flang, the developers are split across these projects. And hence the contributions have reduced.

Some of the contributions from Arm and AMD can be seen in the following links.
https://github.com/flang-compiler/flang/pulls?q=is%3Apr+author%3Ashivaramaarao
https://github.com/flang-compiler/flang/pulls?q=is%3Apr+author%3Abhuvanendrakumarn
https://github.com/flang-compiler/flang/pulls?q=is%3Apr+author%3Aalokkrsharma
https://github.com/flang-compiler/flang/pulls?q=is%3Apr+author%3Apawosm-arm
https://github.com/flang-compiler/flang/pulls?q=is%3Apr+author%3Akaadam
https://github.com/flang-compiler/flang/pulls?q=is%3Apr+author%3Akiranchandramohan+
