### ISSUE TITLE
Error while compiling libpgmath

### ISSUE THREAD

**Issue by bhatuzdaname** [flang-compiler/flang#498]
Compiling libpgmath with clang trunk (r334256) gives the following error:

/flang/runtime/libpgmath/lib/common/log/fma3/fdlog1.cpp:37:9: error: argument should be a value from 0 to 15
    t = _mm_blend_epi32(INT2DBL_HI, t, H55_D);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/build/lib/clang/7.0.0/include/avx2intrin.h:796:12: note: expanded from macro '_mm_blend_epi32'
  (__m128i)__builtin_ia32_pblendd128((__v4si)(__m128i)(V1), \
           ^
1 error generated.

Is this a bug with clang or with libpgmath?
 The change in clang that introduced this error is r334249.
" [X86] Add builtins for blend with immediate control to enforce target feature requirements and check immediate range."

**Comment by d-parks** [comment]
Hi,

I don't understand what the problem is given the definition and use of H55_D:
[dparks@vnc fma3]$ grep H55_D *
fdlog1.cpp:    t = _mm_blend_epi32(INT2DBL_HI, t, H55_D); 
fdlog2.cpp:    t = _mm_blend_epi32(INT2DBL_HI, t, H55_D); 
fdlog4.cpp:    t = _mm256_blend_epi32(INT2DBL_HI, t, H55_D); 
fdlog8.cpp:    t = _mm512_mask_blend_epi32((H55_D<<8)|H55_D, INT2DBL_HI, t);
fdlog_defs.h:#define H55_D                     0x55
[dparks@vnc fma3]$ 

Would you be able to elaborate?

Thank you.
